// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using HotelManagement.Entities;

namespace HotelManagement.Context
{
    public partial class FrontEndReservationContext : DbContext
    {
        public FrontEndReservationContext()
        {
        }

        public FrontEndReservationContext(DbContextOptions<FrontEndReservationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Reservation> Reservations { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=FRONTEND_RESERVATION;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Reservation>(entity =>
            {
                entity.Property(e => e.CardCvc).IsFixedLength();

                entity.Property(e => e.CardType).IsFixedLength();

                entity.Property(e => e.PaymentType).IsFixedLength();

                entity.Property(e => e.RoomFloor).IsFixedLength();

                entity.Property(e => e.RoomNumber).IsFixedLength();

                entity.Property(e => e.RoomType).IsFixedLength();

                entity.Property(e => e.ZipCode).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}